Automação Web e busca de informações com Python 3

Buscar preço do Euro, Dólar e Ouro

In [5]:
#Passo 1: Pegar cotação do ouro
#Passo 2: Pegar cotação do dólar
#Passo 3:Pegar cotação do euro
#Passo 4: Atualizar a base de dados
#Passo 5: Recalcular os preços
#Passo 6: Exportar a base atualizada

In [6]:
from selenium import webdriver
navegador = webdriver.Chrome()

#Pegando a cotação do dólar
navegador.get('https://www.google.com/search?q=cota%C3%A7%C3%A3o+dolar&oq=cota&aqs=chrome.0.0i131i433i512j69i57j0i433i512j0i131i433i512j0i433i512j0i512j0i131i433i512j0i433i512l3.1726j1j7&sourceid=chrome&ie=UTF-8')#abrindo o link para ver o dólar
cotacao_dolar = navegador.find_element('xpath', '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')#Pegando o preço do dólar
print(f'{cotacao_dolar:.2f}')

#Pegando a cotação do euro
navegador.get('https://www.google.com/search?q=cota%C3%A7%C3%A3o+euro&oq=cota%C3%A7%C3%A3o+euro&aqs=chrome.0.0i131i433i512l3j0i433i512j0i512l6.1822j1j7&sourceid=chrome&ie=UTF-8')#abrindo o link da cotação do euro
cotacao_euro = navegador.find_element('xpath', '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')#Pegando o preço do euro
print(f'{cotacao_euro:2f}')

#Pegando cotação do ouro
navegador.get('https://www.melhorcambio.com/ouro-hoje')#Site da cotação do ouro
cotacao_ouro = navegador.find_element('xpath', '//*[@id="comercial"]').get_attribute('value')#Pegando o preço do ouro
cotacao_ouro = cotacao_ouro.replace(',', '.')
print(f'{cotacao_ouro:.2f}')

5.1479
5.57372914
317.65

In [7]:
#Importando a base de dados e atualizar a base
import pandas as pd

dados = pd.read_excel('Produtos.xlsx')

dados.loc[dados['Moeda'] == 'Dólar', 'Cotação'] = float(cotacao_dolar)#Ajustando a tabela para a cotação dólar
dados.loc[dados['Moeda'] == 'Euro', 'Cotação'] = float(cotacao_euro)#Ajustando a tabela para a cotação euro
dados.loc[dados['Moeda'] == 'Ouro', 'Cotação'] = float(cotacao_ouro)#Ajustando a tabela para a cotação ouro

#Recalculando os preços
dados['Preço de Compra'] = dados['Preço Original'] * dados['Cotação']
dados['Preço de Venda'] = dados['Preço de Compra'] * dados['Margem']
print(dados)

#Exportando uma base de dados NOVA 
dados.to_excel('Produtos NOVO.xlsx', index=False)
navegador.quit()

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.147900,5147.848521,1.40,7206.987929
1,Carro Renault,4500.00,Euro,5.573729,25081.781130,2.00,50163.562260
2,Notebook Dell,899.99,Dólar,5.147900,4633.058521,1.70,7876.199486
3,IPhone,799.00,Dólar,5.147900,4113.172100,1.70,6992.392570
4,Carro Fiat,3000.00,Euro,5.573729,16721.187420,1.90,31770.256098
5,Celular Xiaomi,480.48,Dólar,5.147900,2473.462992,2.00,4946.925984
6,Joia 20g,20.00,Ouro,317.650000,6353.000000,1.15,7305.950000